name: Test RUNNER_TOOL_CACHE

on:
  push:
    branches: [ main ]

jobs:
  cache:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: xiaq/action-test@main
    - name: ls /usr/local/bin
      run: |
        ls -l /usr/local/bin