name: Test RUNNER_TOOL_CACHE

on:
  push:
    branches: [ main ]

jobs:
  cache:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: ls
      run: |
        ls -l $RUNNER_TOOL_CACHE
        if test -d $RUNNER_TOOL_CACHE/elvish; then
          echo elvish directory exists
          ls -lR $RUNNER_TOOL_CACHE/elvish
        fi
    - uses: xiaq/action-test
    - name: ls again
      run: |
        ls -l $RUNNER_TOOL_CACHE
        if test -d $RUNNER_TOOL_CACHE/elvish; then
          echo elvish directory exists
          ls -lR $RUNNER_TOOL_CACHE/elvish
        fi