name: Test RUNNER_TOOL_CACHE

on:
  push:
    branches: [ main ]

jobs:
  cache:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: ls
      run: |
        ls -l $RUNNER_TOOL_CACHE
        if test -d $RUNNER_TOOL_CACHE/elvish; then
          echo elvish directory exists
          ls -lR $RUNNER_TOOL_CACHE/elvish
        fi
        if test -d $RUNNER_TOOL_CACHE/go; then
          echo go directory exists
          ls -lR $RUNNER_TOOL_CACHE/go
        fi
    - name: Populate
      run: |
        mkdir -p $RUNNER_TOOL_CACHE/elvish/0.1.0/amd64
        echo something >> $RUNNER_TOOL_CACHE/elvish/0.1.0/amd64/${{ github.sha }}
        touch $RUNNER_TOOL_CACHE/elvish/0.1.0/amd64.complete
    - name: ls again
      run: |
        ls -l $RUNNER_TOOL_CACHE
        if test -d $RUNNER_TOOL_CACHE/elvish; then
          echo elvish directory exists
          ls -lR $RUNNER_TOOL_CACHE/elvish
        fi