name: Test Elvish

on:
  push:
    branches: [ main ]

jobs:
  cache:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: xiaq/action-test@main
    - name: Show PATH
      run: |
        echo $PATH
        echo /usr/local/bin >> $GITHUB_PATH
    - name: Run with Elvish
      run: |
        echo This is Elvish $version
      shell: elvish