name: Test Elvish

on:
  push:
    branches: [ main ]

jobs:
  see_env:
    runs-on: windows-latest
    steps:
    - name: Show environment
      run: |
        echo $Env:RUNNER_TOOL_CACHE

  test_elvish:
    strategy:
      matrix:
        os: [ubuntu]
    runs-on: ${{ matrix.os }}-latest
    steps:
    - uses: xiaq/action-test@main
    - name: Run with Elvish
      run: |
        echo This is Elvish $version
      shell: elvish {0}