name: Test Elvish

on:
  push:
    branches: [ main ]

jobs:
  test_elvish:
    strategy:
      matrix:
        os: [ubuntu, macos, windows]
    runs-on: ${{ matrix.os }}-latest
    steps:
    - uses: xiaq/action-test@main
    - name: Run with Elvish
      run: |
        echo This is Elvish $version
      shell: elvish {0}